default:
    resource: "@DunglasTodoMVCBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /

post:
    resource: "@DunglasTodoMVCBundle/Controller/TodoController.php"
    type:     rest
    prefix:   /api
